Nafis
anakpacil/tipsen pull request #10
Opened 2018-10-29 15:02 UTC by annafis1

Added my name in list absen

2018-10-29 15:22 UTC, laymonage requested changes

2018-10-29 15:22 UTC, laymonage commented on README.md
> +| 7.  | [Athallah Annafis][annafis1]			  | 2017	 | Ilmu Komputer	|
Maaf fis, boleh diganti biar pake spasi aja ga, bukan tab? Soalnya jadi ga seragam nih tabulasinya, hehe.

2018-10-31 13:18 UTC, annafis1 commented
Otw

On Mon, Oct 29, 2018 at 10:25 PM sage <notifications@github.com> wrote:

> *@laymonage* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/anakpacil/tipsen/pull/10#discussion_r228972691>:
>
> > @@ -16,6 +16,7 @@ Untuk berkontribusi, silakan lihat [CONTRIBUTING.md][contributing.md].
>  | 4.  | [Giovan Isa Musthofa][giovanism]          | 2017     | Ilmu Komputer    |
>  | 5.  | [Muhammad Azhar Rais Zulkarnain][azharaiz]| 2017     | Ilmu Komputer    |
>  | 6.  | [Ahmad Fauzan A.I.][ahmad-fauzan458]      | 2017     | Ilmu Komputer    |
> +| 7.  | [Athallah Annafis][annafis1]			  | 2017	 | Ilmu Komputer	|
>
> Maaf fis, boleh diganti biar pake spasi aja ga, bukan tab? Soalnya jadi ga
> seragam nih tabulasinya, hehe.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/anakpacil/tipsen/pull/10#pullrequestreview-169360148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AfjNse8gOUL17HjzF3bmfmJDCWFRwf66ks5upx3_gaJpZM4X_X-V>
> .
>

2018-10-31 13:32 UTC, laymonage approved these changes

2018-10-31 13:32 UTC, merged

2018-10-31 13:32 UTC, laymonage commented
Mantap gan