Add arnastria
anakpacil/tipsen pull request #5
Opened 2018-10-25 08:04 UTC by Arnastria

Hi, tipsen ya gan

2018-10-25 09:05 UTC, giovanism commented on README.md
> +[arnastria]: https://githubmcom/arnastria
Tautan Anda saltik ya.

2018-10-25 09:14 UTC, giovanism requested changes
Thanxx @Arnastria sudah bikin PR, tapi sebelum bisa di-merge, tolong betulkan dulu review di bawah.

2018-10-25 09:14 UTC, giovanism commented on README.md
> +[arnastria]: https://githubmcom/arnastria
Tautan Anda saltik ya, @Arnastria

2018-10-25 09:26 UTC, Arnastria commented on README.md
> +[arnastria]: https://githubmcom/arnastria
wah terimakasih telah memberi tahu kesalahan, akan saya perbaiki

2018-10-25 09:41 UTC, giovanism commented
**Pilih jawaban yang paling tepat!**

Teman Anda ramawajdika baru-baru ini menambahkan perubahan baru ke repository, sehingga pekerjaan yang Anda kerjakan mengalami conflict. Hal pertama yang harus Anda lakukan agar dapat *merge* ke master tanpa conflict, adalah:

a. git clone
b. git remote
c. git pull
d. git push
e. git merge

2018-10-31 14:02 UTC, laymonage commented
@Arnastria mau _resolve_ sendiri atau mau di-_resolve_-in?

2026-04-23 09:11 UTC, closed without merging